services:
  mail-sender:
    container_name: valura-mail
    build: .
    ports:
      - "3015:3015"
    env_file:
      - .env
    restart: unless-stopped
    labels:
      - "traefik.http.middlewares.cors.headers.accessControlAllowOriginList=https://valura.mx,https://www.valura.mx"
      - "traefik.http.middlewares.cors.headers.accessControlAllowMethods=POST,OPTIONS"
      - "traefik.http.middlewares.cors.headers.accessControlAllowHeaders=Content-Type,Accept"
      - "traefik.http.routers.mail-sender.middlewares=cors@docker"
      - "traefik.http.routers.mail-sender.rule=PathPrefix(`/api/cotizacion`)"
      - "traefik.http.routers.mail-sender.entrypoints=websecure"
      - "traefik.http.routers.mail-sender.tls=true"
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
